[versions]
minecraft = "1.21.1"
mdg = "2.0.+"
neoforge = "21.1.234"
parchment = "2024.11.17"

create = "6.0.10-280"
ponder = "1.0.82+mc1.21.1"
registrate = "MC1.21-1.3.0+67"
flywheel = "1.0.6"

sable = "2.0.3"
sable-companion = "1.4.0"
simulated-suite = "1.3.0"
veil = "3.4.0"

[libraries]
create = { module = "com.simibubi.create:create-1.21.1", version.ref = "create" }
ponder = { module = "net.createmod.ponder:ponder-neoforge", version.ref = "ponder" }
registrate = { module = "com.tterrag.registrate:Registrate", version.ref = "registrate" }

flywheel-api = { module = "dev.engine-room.flywheel:flywheel-neoforge-api-1.21.1", version.ref = "flywheel" }
flywheel = { module = "dev.engine-room.flywheel:flywheel-neoforge-1.21.1", version.ref = "flywheel" }

sable = { module = "dev.ryanhcode.sable:sable-neoforge-1.21.1", version.ref = "sable" }
sable-companion = { module = "dev.ryanhcode.sable-companion:sable-companion-1.21.1", version.ref = "sable-companion" }
veil = { module = "foundry.veil:veil-neoforge-1.21.1", version.ref = "veil" }
simulated = { module = "dev.simulated_team.simulated:simulated-neoforge-1.21.1", version.ref = "simulated-suite" }
aeronautics = { module = "dev.eriksonn.aeronautics:aeronautics-neoforge-1.21.1", version.ref = "simulated-suite" }
offroad = { module = "dev.ryanhcode.offroad:offroad-neoforge-1.21.1", version.ref = "simulated-suite" }

[bundles]
simulated-suite = [ "sable", "simulated", "aeronautics", "offroad" ]
sable-libs = [ "sable-companion", "veil" ]

[plugins]
mdg = { id = "net.neoforged.moddev", version.ref = "mdg" }
